import { Transaction, Mission, Badge, UserProfile, ClothingItem, Character } from './types';

export const initialTransactions: Transaction[] = [
  {
    id: '1',
    type: 'income',
    amount: 3500,
    description: 'Projeto Freelance - Site Institucional',
    category: 'Freelance',
    date: new Date(2024, 2, 15),
  },
  {
    id: '2',
    type: 'expense',
    amount: 150,
    description: 'Supermercado',
    category: 'Alimentação',
    date: new Date(2024, 2, 14),
  },
  {
    id: '3',
    type: 'expense',
    amount: 89.90,
    description: 'Assinatura Adobe Creative',
    category: 'Ferramentas',
    date: new Date(2024, 2, 13),
  },
  {
    id: '4',
    type: 'income',
    amount: 1200,
    description: 'Consultoria',
    category: 'Freelance',
    date: new Date(2024, 2, 12),
  },
  {
    id: '5',
    type: 'expense',
    amount: 45,
    description: 'Uber',
    category: 'Transporte',
    date: new Date(2024, 2, 11),
  },
];

export const initialMissions: Mission[] = [
  {
    id: '1',
    title: 'Primeiros Passos',
    description: 'Registre 5 transações',
    progress: 5,
    target: 5,
    xpReward: 50,
    completed: true,
  },
  {
    id: '2',
    title: 'Economista Iniciante',
    description: 'Economize R$ 500 este mês',
    progress: 315,
    target: 500,
    xpReward: 100,
    completed: false,
  },
  {
    id: '3',
    title: 'Disciplina Financeira',
    description: 'Registre transações por 7 dias seguidos',
    progress: 4,
    target: 7,
    xpReward: 75,
    completed: false,
  },
  {
    id: '4',
    title: 'Mestre das Finanças',
    description: 'Complete 20 transações',
    progress: 5,
    target: 20,
    xpReward: 150,
    completed: false,
  },
];

export const initialBadges: Badge[] = [
  {
    id: '1',
    name: 'Primeiro Passo',
    description: 'Registrou sua primeira transação',
    unlocked: true,
    icon: 'trophy',
  },
  {
    id: '2',
    name: 'Economizador',
    description: 'Economizou R$ 1000',
    unlocked: false,
    icon: 'piggy-bank',
  },
  {
    id: '3',
    name: 'Disciplinado',
    description: 'Manteve registro por 30 dias',
    unlocked: false,
    icon: 'calendar-check',
  },
  {
    id: '4',
    name: 'Mestre Financeiro',
    description: 'Atingiu nível 10',
    unlocked: false,
    icon: 'crown',
  },
];

export const initialUserProfile: UserProfile = {
  name: 'Jogador',
  level: 5,
  xp: 45,
  xpToNextLevel: 100,
  totalTransactions: 5,
  streak: 4,
  coins: 5000,
};

export const clothingItems: ClothingItem[] = [
  {
    id: 'head-1',
    name: 'Óculos Neon',
    category: 'head',
    price: 150,
    rarity: 'common',
    emoji: '😎',
  },
  {
    id: 'head-2',
    name: 'Coroa Dourada',
    category: 'head',
    price: 500,
    rarity: 'rare',
    emoji: '👑',
  },
  {
    id: 'head-3',
    name: 'Chapéu Gamer',
    category: 'head',
    price: 200,
    rarity: 'uncommon',
    emoji: '🎮',
  },
  {
    id: 'head-4',
    name: 'Capacete Futurista',
    category: 'head',
    price: 800,
    rarity: 'epic',
    emoji: '🛸',
  },
  {
    id: 'head-5',
    name: 'Diadema Legendária',
    category: 'head',
    price: 1500,
    rarity: 'legendary',
    emoji: '✨',
  },

  {
    id: 'shirt-1',
    name: 'Camiseta Casual',
    category: 'shirt',
    price: 100,
    rarity: 'common',
    emoji: '👕',
  },
  {
    id: 'shirt-2',
    name: 'Jaqueta Neon',
    category: 'shirt',
    price: 300,
    rarity: 'uncommon',
    emoji: '🧥',
  },
  {
    id: 'shirt-3',
    name: 'Blazer Profissional',
    category: 'shirt',
    price: 400,
    rarity: 'uncommon',
    emoji: '🎩',
  },
  {
    id: 'shirt-4',
    name: 'Terno Executivo',
    category: 'shirt',
    price: 750,
    rarity: 'epic',
    emoji: '💼',
  },
  {
    id: 'shirt-5',
    name: 'Roupa Cósmica',
    category: 'shirt',
    price: 2000,
    rarity: 'legendary',
    emoji: '🌌',
  },

  {
    id: 'pants-1',
    name: 'Calça Jeans',
    category: 'pants',
    price: 120,
    rarity: 'common',
    emoji: '👖',
  },
  {
    id: 'pants-2',
    name: 'Calça Neon',
    category: 'pants',
    price: 280,
    rarity: 'uncommon',
    emoji: '💥',
  },
  {
    id: 'pants-3',
    name: 'Calça Executiva',
    category: 'pants',
    price: 350,
    rarity: 'uncommon',
    emoji: '📊',
  },
  {
    id: 'pants-4',
    name: 'Calça Futurista',
    category: 'pants',
    price: 600,
    rarity: 'epic',
    emoji: '🚀',
  },
  {
    id: 'pants-5',
    name: 'Calça Infinita',
    category: 'pants',
    price: 1800,
    rarity: 'legendary',
    emoji: '∞',
  },

  {
    id: 'feet-1',
    name: 'Sapato Casual',
    category: 'feet',
    price: 80,
    rarity: 'common',
    emoji: '👟',
  },
  {
    id: 'feet-2',
    name: 'Tênis Gamer',
    category: 'feet',
    price: 250,
    rarity: 'uncommon',
    emoji: '⚡',
  },
  {
    id: 'feet-3',
    name: 'Sapato Social',
    category: 'feet',
    price: 300,
    rarity: 'uncommon',
    emoji: '✨',
  },
  {
    id: 'feet-4',
    name: 'Botas Cyberpunk',
    category: 'feet',
    price: 700,
    rarity: 'epic',
    emoji: '🤖',
  },
  {
    id: 'feet-5',
    name: 'Sapato Mágico',
    category: 'feet',
    price: 1600,
    rarity: 'legendary',
    emoji: '🌟',
  },
];

export const initialCharacter: Character = {
  head: 'head-1',
  shirt: 'shirt-1',
  pants: 'pants-1',
  feet: 'feet-1',
};
